import scala.util.Random
import User._

object CommandParser {
  // Command patterns organized by category
  private val commandPatterns: Map[String, List[String]] = Map(
    "tips" -> List(
      "i want to be healthy",
      "tip",
      "health",
      "wellness",
      "fitness",
      "healthy",
      "give me a healthy tip",
      "tell me a wellness tip",
      "i need a healthy lifestyle",
      "how can i stay healthy?",
      "i want to improve my health",
      "healthy advice please",
      "tips for eating better",
      "tell me how to be healthy",
      "i need a wellness tip",
      "how do i build healthy habits",
      "i want to live a healthy life",
      "i just want to feel better",
      "how do i stay fit",
      "give me some good health habits",
      "i want more energy",
      "what are good lifestyle tips",
      "what should i eat to stay healthy",
      "i need better daily habits",
      "help me fix my health routine",
      "how can i feel more energetic",
      "give me healthy life advice",
      "i want to boost my immunity",
      "tips for living longer",
      "help me stay in shape",
      "what are some health tips",
      "i want to be more active",
      "daily health tips please",
      "can you give me health advice",
      "how do i stay strong and healthy",
      "i need tips to eat clean",
      "how to avoid junk food",
      "give me advice for a balanced life",
      "i want a better health routine",
      "how can i avoid getting sick",
      "tips to improve my energy levels",
      "teach me healthy habits",
      "i want to fix my health",
      "how can i feel better every day",
      "give me a healthy reminder",

      // Additional short/keyword triggers for parsing
      "energy",
      "immunity",
      "stay fit",
      "health habits",
      "better routine",
      "more active",
      "boost health",
      "healthy habits",
      "feel better",
      "stay healthy",
      "healthy life",
      "stay strong",
      "live longer",
      "wellness tip",
      "health advice",
      "lifestyle tips",
      "health tip"
    ),
    "smallTalkTriggers" -> List(
      "how are you",
      "how r u",
      "how are u",
      "hw are you",
      "how ru",
      "how r you",
      "how r u?",
      "what are you doing",
      "wat r u doing",
      "wut r u doing",
      "whatcha doing",
      "whatchu doing",
      "talk to me",
      "tlk to me",
      "tak to me",
      "tok to me",
      "tawk to me",
      "speak with me",
      "spk with me",
      "speek with me",
      "can we chat",
      "can we tlk",
      "can we talk",
      "can we tok",
      "wanna talk",
      "say something",
      "say smthing",
      "say somethng",
      "say sumthing",
      "are you there",
      "r u there",
      "ru there",
      "are u ther",
      "are you ther",
      "are you online",
      "r u online",
      "ru online",
      "r u onlne",
      "can you talk",
      "can u talk",
      "can u tlk",
      "cn u talk",
      "how's it going",
      "howz it going",
      "hw's it going",
      "hows it goin",
      "how iz it going",
      "how do you feel",
      "how r u feeling",
      "how do u feel",
      "what's up",
      "wats up",
      "whats up",
      "sup",
      "wassup",
      "wazzup",
      "wasup",
      "do you want to talk",
      "do u want to talk",
      "do u wanna talk",
      "i want to talk",
      "i wanna talk",
      "i wanta talk",
      "let's chat",
      "lets chat",
      "let us chat",
      "lets tlk",
      "just wanted to talk",
      "jus wanna talk",
      "jus wanted to tlk",
      "need someone to talk to",
      "need someone to tlk to",
      "are you awake",
      "r u awake",
      "are u awake",
      "ru awake",
      "can we talk for a bit",
      "can we tlk",
      "need someone to talk to",
      "need someone to tlk to",
      "are you awake",
      "r u awake",
      "are u awake",
      "ru awake",
      "can we talk for a bit",
      "can we tlk for a bit",
      "can we chat for a bit",
      "feeling bored",
      "i am bored",
      "im bored",
      "am bored",
      "check in",
      "checking in",
      "just checking in",
      "you there",
      "are you still there",
      "u still there",
      "just saying hello",
      "just passing by",
      "whats going on",
      "whats going on",
      "what is going on",
      "how have you been",
      "how u been",
      "how have u been",
      "how've you been",
      "how is your day",
      "hows your day",
      "how is ur day",
      "howz ur day",
      "talk now",
      "chat now",
      "say something now",
      "speak now"
    ),
    "greeting" -> List(
      // Standard
      "hi",
      "hello",
      "hey",
      "hey there",
      "hi there",
      "good morning",
      "good afternoon",
      "good evening",

      // Casual/slang
      "yo",
      "sup",
      "what's up",
      "howdy",
      "heya",
      "greetings",
      "salutations",
      "hiya",
      "hello there",
      "hey there",
      "hi there",
      "hello friend",
      "hey friend",
      "hi friend",
      "hello buddy",
      "hey buddy",
      "hi buddy",

      // Typos and variants
      "hii",
      "hiii",
      "helloo",
      "hellooo",
      "heyy",
      "heyyy",
      "hithere",
      "hitheir",
      "hither",
      "hellow",
      "hallo",
      "hellou",
      "helo",
      "hullo",
      "heytheir",
      "heythere",
      "hay",
      "hallo",
      "hullo",
      "hallo there",
      "hullo there",

      // Time-specific typos
      "gud morning",
      "good mornin",
      "goodmornin",
      "good moring",
      "good afternon",
      "good aftrnoon",
      "goodevening",
      "good evning",
      "gud evening",
      "good eveing",
      "morning",
      "afternoon",
      "evening",
      "night",
      "good day",
      "good nite",
      "goodnight",

      // Combined/run-on
      "hihello",
      "hellohey",
      "heyhi",
      "hi there friend",
      "hello there friend",
      "hey there friend",
      "hi there buddy",
      "hello there buddy",
      "hey there buddy"
    ),
    "reaction" -> List(
      // Standard expressions
      "wow",
      "whoa",
      "cool",
      "awesome",
      "amazing",
      "nice",
      "great",
      "impressive",
      "fantastic",
      "super",
      "sweet",
      "neat",
      "rad",
      "excellent",
      "brilliant",
      "incredible",
      "terrific",
      "fabulous",
      // Casual/slang
      "dang",
      "damn",
      "heck",
      "yo",
      "yep",
      "yup",
      "whoop",
      "boom",
      "hot damn",
      "no way",
      "get out",
      "shut up",
      "for real",
      "that's wild",
      "that's crazy",
      "that's dope",
      "that's lit",
      // Natural language variations
      "that's amazing",
      "that's awesome",
      "that's cool",
      "that's great",
      "that's impressive",
      "that's incredible",
      "that's fantastic",
      "really cool",
      "pretty cool",
      "so cool",
      "very cool",
      "lol",
      "lmao",
      "haha",
      "how cool",
      "how awesome",
      "how amazing",
      "how great",
      "this is awesome",
      "this is amazing",
      "this is cool",
      // Typos and variants
      "wwo",
      "woow",
      "woww",
      "w0w",
      "whow",
      "whoa",
      "woah",
      "aww",
      "awe",
      "awesum",
      "awsome",
      "amazin",
      "gr8",
      "cooll",
      "coool",
      "kool",
      "kewl",
      "ncie",
      "nicce",
      "impressiv",
      "fantastik",
      "supr",
      "sweat",
      "neeto",
      "exellent",
      "briliant",
      "incredble",
      "teriffic",
      // Slang typos
      "dangg",
      "dam",
      "hecc",
      "yoo",
      "yepp",
      "yupp",
      "thats wild",
      "thats cray",
      "thats dope",
      "thats lit",
      "noo way",
      "getout",
      "shutup",
      "4 real",
      "fr"
    ),
    "funny" -> List(
      "joke",
      "tell me a joke",
      "humor",
      "comedy",
      "laugh",
      "hilarious",
      "amusing",
      "make me laugh",
      "that's funny",
      "funny story"
    ),
    "thanks" -> List(
      // Standard
      "thank",
      "thanks",
      "thank you",
      "thank you very much",
      "thank you so much",
      "thanks a lot",
      "thanks a bunch",
      "thanks very much",
      "many thanks",
      "much appreciated",
      "i appreciate it",
      "i appreciate that",
      "i appreciate you",
      "thanks for your help",
      "thanks for helping",
      "thanks for the help",
      "thank you for your help",
      "thank you for helping",
      "thank you for the help",

      // Slang/abbreviations
      "thx",
      "thanx",
      "tnx",
      "ty",
      "tysm",
      "tyvm",
      "thanksies",
      "thanks a ton",
      "thanks a million",
      "big thanks",
      "huge thanks",
      "super thanks",
      "thanks a bunch",
      "thanks a heap",
      "thanks a load",
      "thanks a million",
      "thanks a ton",
      "thanks a zillion",

      // Typos
      "thankx",
      "thnks",
      "thaks",
      "thansk",
      "thankyou",
      "thank u",
      "thankyu",
      "thanky",
      "thx u",
      "thnku",
      "thanks alot",
      "thanksa lot",
      "thank youv ery much",
      "thankyou very much",
      "thankyouverymuch",
      "thnk u",
      "thks",
      "tks",
      "tank you",
      "tenk you",
      "fank you",
      "thanksss",
      "thankies",
      "thank you so much",
      "thank you very much",
      "thank you a lot",
      "thank you a bunch",
      "thank you a ton",
      "thank you a million"
    ),
    "capabilities" -> List(
      // Direct queries
      "what can you do",
      "what else can you do",
      "what are your capabilities",
      "what are you capable of",
      "what do you support",
      "what functions do you have",
      "what are my options",
      "what options do i have",
      "show me options",
      "show features",
      "list features",
      "what do you offer",
      "what can you help me with",
      "what can you do for me",
      "what are you good at",
      "what are your features",
      "what are your functions",
      "what are your tools",
      "what are your capabilities",
      "what are your skills",
      "what are your abilities",
      "what are your powers",

      // Help/commands
      "help",
      "help menu",
      "show commands",
      "show help",
      "what are my choices",
      "menu",
      "options",
      "tools",
      "what tools do you have",
      "show me what you can do",
      "what are your commands",
      "what commands do you have",
      "what can i ask you",
      "what can i do with you",
      "how can you help me",
      "how can you assist me",

      // Exploratory
      "what else is there",
      "what more can you do",
      "anything else",
      "can you do more",
      "do you have other features",
      "what are the possibilities",
      "what else is possible",
      "what are your functions",
      "what else can you help with",
      "what other things can you do",
      "what other features do you have",
      "what other capabilities do you have",
      "what other functions do you have",
      "what other tools do you have",

      // Typos/slang
      "wat can u do",
      "what can u do",
      "what can you du",
      "what else can u do",
      "what else can youd o",
      "help me",
      "halp",
      "show me the options",
      "what are my optins",
      "featurs",
      "what do you ofer",
      "what else is their",
      "wat can u do",
      "wat can u help with",
      "wat r ur features",
      "wat r ur functions",
      "wat r ur capabilities",
      "wat r ur skills"
    ),
    "fact" -> List(
      // Standard queries
      "fact",
      "random fact",
      "tell me a fact",
      "give me a fact",
      "interesting fact",
      "fun fact",
      "cool fact",
      "science fact",
      "useless fact",
      "weird fact",
      "did you know",
      "share a fact",
      "give me a random fact",
      "tell me a random fact",
      "i want a fact",
      "i need a fact",
      "can you give me a fact",
      "can you tell me a fact",
      "can you share a fact",

      // Natural language variations
      "tell me something interesting",
      "tell me something cool",
      "tell me something fun",
      "tell me something random",
      "share a fact",
      "give me trivia",
      "teach me something",
      "what's a fun fact",
      "what's an interesting fact",
      "what's a cool fact",
      "what's a random fact",
      "i want to learn something",
      "i want to know something",
      "i need to learn something",
      "i need to know something",
      "can you teach me something",
      "can you tell me something",

      // Conversational/implied requests
      "something interesting",
      "something cool",
      "something fun",
      "something random",
      "anything interesting",
      "anything fun",
      "learn something",
      "surprise me",
      "enlighten me",
      "tell me more",
      "tell me something",
      "share something",
      "give me something",
      "show me something",
      "teach me something",

      // Typos/slang
      "fax",
      "fakt",
      "randum fact",
      "interesing fact",
      "funfax",
      "give me fakt",
      "tell me somethin cool",
      "somethin interesting",
      "did u know",
      "wats a fact",
      "sumthin cool",
      "tell me sumthin",
      "give me sumthin",
      "show me sumthin",
      "teach me sumthin",
      "learn sumthin"
    ),
    "bmi" -> List(
      // Core terms
      "bmi",
      "body mass index",
      "my bmi",
      "check bmi",
      "compute bmi",
      "measure bmi",
      "get bmi",
      "find bmi",
      "determine bmi",
      "figure out bmi",

      // Natural language variations
      "what is my bmi",
      "whats my bmi",
      "figure out my bmi",
      "determine my bmi",
      "i want to know my bmi",
      "tell me my bmi",
      "show me my bmi",
      "get my bmi",
      "what would my bmi be",
      "i need to know my bmi",
      "can you tell me my bmi",
      "what's my body mass index",
      "what is my body mass index",
      "can you help me find my bmi",
      "can you help me determine my bmi",
      "can you help me figure out my bmi",

      // Common misspellings/simplifications
      "body mass",
      "mass index",
      "bm i",
      "bodymass index",
      "body mass indx",
      "bmi calc",
      "my body mass",
      "my mass index",
      "bodymass",
      "body mass indx",
      "mass indx",
      "bm i",
      "bmi calc"
    ),
    "ffmi" -> List(
      // Core terms
      "ffmi",
      "fat free mass index",
      "ffmi calculator",
      "my ffmi",
      "check ffmi",
      "compute ffmi",
      "measure ffmi",
      "get ffmi",
      "find ffmi",
      "determine ffmi",
      "figure out ffmi",

      // Natural language variations
      "what is my ffmi",
      "whats my ffmi",
      "figure out my ffmi",
      "determine my ffmi",
      "i want to know my ffmi",
      "tell me my ffmi",
      "show me my ffmi",
      "get my ffmi",
      "what would my ffmi be",
      "i need to know my ffmi",
      "can you tell me my ffmi",
      "what's my fat free mass index",
      "what is my fat free mass index",
      "can you help me find my ffmi",
      "can you help me determine my ffmi",
      "can you help me figure out my ffmi",

      // Common alternative names/phrases
      "fat free mass",
      "fat free index",
      "muscle mass index",
      "lean mass index",
      "lean body mass index",
      "muscle index",
      "lean mass",
      "muscle mass",

      // Common misspellings/typos
      "ffim",
      "what about my ffmi",
      "fatfree mass index",
      "fat free mass indx",
      "fat free masss index",
      "ffmi calc",
      "free fat mass index",
      "ff mi"
    ),
    "workout" -> List(
      // General workout terms
      "workout",
      "exercise",
      "training",
      "gym",
      "lift",
      "lifting",
      "work out",
      "start working out",
      "begin working out",
      "training program",
      "workout program",
      "exercise routine",
      "workout routine",
      "training routine",
      "fitness routine",
      "i want to workout",
      "i need to workout",
      "i want to exercise",
      "i need to exercise",
      "i want to train",
      "i need to train",
      "can you help me workout",
      "can you help me exercise",
      "can you help me train",
      "can you now help me train",
      "can you give me a workout",
      "can you give me an exercise",
      "can you give me a training",

      // Workout types
      "bodybuilding",
      "calisthenics",
      "martial arts",
      "strength training",
      "powerlifting",
      "crossfit",
      "hiit",
      "cardio",
      "endurance training",
      "functional training",
      "weight training",
      "resistance training",

      // Split types
      "push pull legs",
      "ppl",
      "upper lower",
      "full body",
      "bro split",
      "pro split",
      "strength split",
      "hypertrophy split",

      // Muscle groups
      "chest workout",
      "back workout",
      "shoulders workout",
      "arms workout",
      "legs workout",
      "core workout",
      "abs workout",
      "biceps workout",
      "triceps workout",
      "forearms workout",
      "quads workout",
      "hamstrings workout",
      "calves workout",
      "glutes workout",
      "lats workout",
      "traps workout",
      "deltoids workout",
      "pecs workout",
      "train chest",
      "train back",
      "train shoulders",
      "train arms",
      "train legs",
      "train core",
      "train abs",

      // Workout goals
      "strength workout",
      "hypertrophy workout",
      "muscle growth workout",
      "muscle gain workout",
      "weight loss workout",
      "fat loss workout",
      "endurance workout",
      "power workout",
      "get stronger",
      "build muscle",
      "lose weight",
      "lose fat",
      "improve endurance",
      "get more power",
      "define muscles",
      "tone up",
      "bulk",
      "cut",

      // Specific requests
      "what exercises should i do",
      "how do i train",
      "need a workout plan",
      "create a workout",
      "design a workout",
      "workout for",
      "training for",
      "exercises for",
      "how to train",
      "how to work out",
      "workout routine for",
      "give me exercises",
      "give me a workout",
      "give me a training plan"
    ),
    "quiz" -> List(
      // Core terms
      "quiz",
      "test",
      "test me",
      "question",
      "ask me",
      "test my knowledge",
      "quiz me",
      "give me a quiz",
      "i want a quiz",
      "i need a quiz",
      "can you quiz me",
      "can you test me",
      "can you ask me",
      "can you question me",

      // Fitness/health variations
      "fitness quiz",
      "health quiz",
      "nutrition quiz",
      "workout quiz",
      "exercise quiz",
      "test my fitness",
      "test my health knowledge",
      "fitness test",
      "health test",
      "i want a fitness quiz",
      "i need a fitness quiz",
      "i want a health quiz",
      "i need a health quiz",
      "i want a nutrition quiz",
      "i need a nutrition quiz",
      "i want a workout quiz",
      "i need a workout quiz",
      "i want an exercise quiz",
      "i need an exercise quiz",

      // Natural language variations
      "give me a quiz",
      "can you quiz me",
      "i want a quiz",
      "start a quiz",
      "begin quiz",
      "challenge me",
      "ask me questions",
      "question me",
      "i want to be quizzed",
      "i need to be quizzed",
      "i want to be tested",
      "i need to be tested",
      "i want to be questioned",
      "i need to be questioned",
      "can you challenge me",
      "can you ask me questions",
      "can you question me",
      "can you test my knowledge",

      // Common typos/slang
      "quizz",
      "qiz",
      "test my knowlege",
      "askme",
      "fitness quizz",
      "helth quiz",
      "workout qiz",
      "test my fitnes",
      "quizz me",
      "test me"
    ),
    "preferences" -> List(
      // Core terms
      "preferences",
      "settings",
      "configure",
      "configuration",
      "profile",
      "set preferences",
      "change preferences",
      "update preferences",
      "set settings",
      "change settings",
      "update settings",

      // Action-oriented phrases
      "change settings",
      "update settings",
      "adjust settings",
      "edit preferences",
      "modify preferences",
      "update preferences",
      "change profile",
      "edit profile",
      "update profile",
      "manage settings",
      "customize settings",

      // Menu/interface terms
      "settings menu",
      "preferences menu",
      "config menu",
      "profile menu",
      "options menu",
      "user menu",
      "show me settings",
      "show me preferences",
      "show me config",
      "show me profile",
      "show me options",
      "show me user",
      "where are settings",
      "where are preferences",
      "where is config",

      // User data phrases
      "my info",
      "personal info",
      "user info",
      "account info",
      "update info",
      "edit info",
      "change info",
      "set info",

      // Common typos/simplifications
      "prefs",
      "settngs",
      "configur",
      "preference",
      "profle",
      "profil",
      "myinformation",
      "personel info",
      "userinformation",
      "acount info"
    ),
    "analytics" -> List(
      // Core terms
      "analytics",
      "stats",
      "statistics",
      "progress",
      "metrics",
      "data",
      "tracking",
      "see analytics",
      "see stats",
      "see statistics",
      "see progress",
      "see metrics",
      "see data",
      "see tracking",

      // Possessive forms
      "my stats",
      "my analytics",
      "my progress",
      "my metrics",
      "my data",
      "my fitness stats",
      "my health stats",
      "my workout stats",
      "show me my stats",
      "show me my analytics",
      "show me my progress",
      "show me my metrics",
      "show me my data",
      "show me my tracking",
      "show me my fitness stats",
      "show me my health stats",
      "show me my workout stats",
      "show me my progress",

      // Action-oriented phrases
      "show stats",
      "show analytics",
      "show progress",
      "show metrics",
      "view stats",
      "view analytics",
      "view progress",
      "view data",
      "track stats",
      "track progress",
      "track analytics",
      "track metrics",
      "check stats",
      "check progress",
      "check analytics",
      "see stats",
      "see progress",
      "see analytics",
      "get stats",
      "get analytics",
      "get progress",

      // Question forms
      "what are my stats",
      "what are my analytics",
      "how is my progress",
      "what do my stats say",
      "how are my analytics",
      "what's my progress",

      // Fitness-specific
      "fitness stats",
      "workout stats",
      "exercise stats",
      "training stats",
      "health analytics",
      "performance stats",
      "body stats",
      "results",
      "achievements",
      "history",
      "workout history",
      "fitness report",

      // Time-based queries
      "weekly stats",
      "monthly progress",
      "daily analytics",
      "yearly metrics",
      "progress report",
      "stats overview"
    ),
    "clear_history" -> List(
      "clear history",
      "delete history",
      "erase history",
      "clear logs",
      "delete logs",
      "erase logs",
      "clear chat",
      "delete chat",
      "erase chat",
      "reset history",
      "reset logs",
      "reset chat",
      "i want to clear history",
      "i need to clear history",
      "i want to delete history",
      "i need to delete history",
      "i want to erase history",
      "i need to erase history",
      "i want to clear logs",
      "i need to clear logs",
      "i want to delete logs",
      "i need to delete logs",
      "i want to erase logs",
      "i need to erase logs",
      "i want to clear chat",
      "i need to clear chat",
      "i want to delete chat",
      "i need to delete chat",
      "i want to erase chat",
      "i need to erase chat",
      "i want to reset history",
      "i need to reset history",
      "i want to reset logs",
      "i need to reset logs",
      "i want to reset chat",
      "i need to reset chat",
      "can you clear history",
      "can you delete history",
      "can you erase history",
      "can you clear logs",
      "can you delete logs",
      "can you erase logs",
      "can you clear chat",
      "can you delete chat",
      "can you erase chat",
      "can you reset history",
      "can you reset logs",
      "can you reset chat"
    ),
    "view_history" -> List(
      "show history",
      "view history",
      "see history",
      "show logs",
      "view logs",
      "see logs",
      "show chat",
      "view chat",
      "see chat",
      "conversation history",
      "chat history",
      "previous conversation",
      "past conversation",
      "earlier conversation",
      "log",
      "logs",
      "history",
      "chat",
      "show log",
      "view log",
      "see log",
      "display history",
      "display logs",
      "display chat",
      "get history",
      "get logs",
      "get chat",
      "check history",
      "check logs",
      "check chat"
    ),
    "exit" -> List(
      // Direct commands
      "exit",
      "quit",
      "end",
      "stop",
      "leave",
      "close",
      "finish",
      "done",

      // Farewell phrases
      "bye",
      "goodbye",
      "good bye",
      "bye bye",
      "see ya",
      "see you",
      "later",
      "talk later",
      "catch you later",
      "gotta go",

      // Time-specific exits
      "good night",
      "goodnight",
      "good morning",
      "good afternoon",
      "good evening",
      "have a good night",

      // Implied exits
      "im done",
      "im finished",
      "that's all",
      "thats all",
      "nothing else",
      "no more",
      "end chat",
      "end conversation"
    ),
    "motivation" -> List(
      // Direct motivation requests
      "motivate me",
      "inspire me",
      "encourage me",
      "pump me up",
      "need motivation",
      "need inspiration",
      "need encouragement",
      "give me motivation",
      "give me inspiration",
      "give me encouragement",
      "motivation quote",
      "inspiration quote",
      "encouragement quote",

      // Body image concerns
      "i am fat",
      "i feel fat",
      "im overweight",
      "i hate my body",
      "i need to lose weight",
      "i want to lose weight",
      "i need to get in shape",
      "im unhappy with my body",
      "im not confident",
      "i need body confidence",

      // Fitness motivation
      "fitness motivation",
      "workout motivation",
      "exercise motivation",
      "training motivation",
      "gym motivation",
      "lifting motivation",
      "running motivation",
      "cardio motivation",
      "strength motivation",

      // Goal-oriented motivation
      "help me stay consistent",
      "help me stay disciplined",
      "help me stay motivated",
      "help me stay inspired",
      "help me stay encouraged",
      "help me stay focused",
      "help me keep going",
      "help me not give up",
      "help me push through",
      "help me break through",

      // Mindset phrases
      "i need a better mindset",
      "i need a positive mindset",
      "i need a growth mindset",
      "i need a strong mindset",
      "i need mental strength",
      "i need mental toughness",
      "i need mental fortitude",
      "i need mental resilience"
    ),
    "diet" -> List(
      // Core terms
      "diet",
      "nutrition",
      "food",
      "meal",
      "eating",
      "diet plan",
      "meal plan",
      "nutrition plan",
      "dieting",
      "dietary",
      "dietary plan",
      "dietary needs",
      "what should i eat",
      "how should i eat",
      "what to eat",
      "personalized diet",
      "personalised diet",

      // Diet types
      "keto",
      "ketogenic",
      "paleo",
      "vegan",
      "vegetarian",
      "mediterranean",
      "low carb",
      "high protein",
      "low fat",
      "intermittent fasting",
      "carnivore",
      "pescatarian",
      "flexitarian",
      "raw food",
      "whole30",
      "dash diet",
      "atkins",
      "zone diet",
      "south beach",
      "weight watchers",

      // Nutritional goals for diet (distinct from workout goals)
      "diet for weight loss",
      "diet for muscle gain",
      "diet for fat loss",
      "bulking diet",
      "cutting diet",
      "maintenance diet",
      "healthy eating",
      "balanced diet",
      "clean eating",
      "body recomposition diet",
      "diet for strength",
      "diet for endurance",
      "diet for performance",
      "diet for recovery",
      "diet for inflammation",
      "diet for gut health",
      "diet for immune support",

      // Meal planning
      "meal prep",
      "meal planning",
      "weekly meals",
      "daily meals",
      "breakfast ideas",
      "lunch ideas",
      "dinner ideas",
      "snack ideas",
      "meal schedule",
      "meal timing",
      "meal frequency",

      // Food categories
      "protein foods",
      "carbohydrate foods",
      "healthy fats",
      "vegetables list",
      "fruits list",
      "grains list",
      "dairy alternatives",
      "nuts and seeds",
      "legumes list",
      "superfoods",

      // Dietary restrictions
      "gluten free",
      "dairy free",
      "nut free",
      "egg free",
      "soy free",
      "shellfish free",
      "fish free",
      "sugar free",
      "low sodium",
      "food allergies",
      "food sensitivities",
      "food intolerances",

      // Specific queries
      "what should i eat",
      "how should i eat",
      "what to eat",
      "how to eat",
      "good diet",
      "healthy diet",
      "balanced diet",
      "clean diet",
      "good meal plan",
      "healthy meal plan",
      "balanced meal plan",
      "clean meal plan",
      "what foods are good for me",
      "what foods should i avoid",
      "what foods are bad",
      "what nutrients do i need",
      "how many calories",
      "macro ratio",
      "micronutrients",
      "nutrient timing"
    )
  )

  // Cache for cleaned patterns to avoid repeated processing
  def inputCleaner(input: String): String = {
    if (input == null || input.trim.isEmpty) return ""
    val cleanerRegex =
      "[\\p{Punct}\\p{Cntrl}\\p{So}@#$%^&*\\-_+=|\\\\\\[\\]{}<>~]+|\\s+".r
    val cleaned = cleanerRegex.replaceAllIn(input.trim.toLowerCase, " ")
    val normalized = cleaned.replaceAll("(.)\\1{2,}", "$1$1")
    normalized.trim
  }

  private val cleanedPatterns: Map[String, Set[String]] = {
    commandPatterns.map { case (command, patterns) =>
      command -> patterns.map(_.toLowerCase.trim).toSet
    }
  }

  def parseInput(input: String): Option[String] = {
    if (input == null || input.trim.isEmpty) return None
    val cleanedInput = inputCleaner(input)

    // Step 1: Try exact matches first (highest priority)
    val exactMatch = cleanedPatterns
      .find { case (_, patterns) =>
        patterns.contains(cleanedInput)
      }
      .map(_._1)

    if (exactMatch.isDefined) return exactMatch

    // Step 2: Try contains matches with word boundary checks
    val words = cleanedInput.split("\\s+").toSet
    val containsMatch = cleanedPatterns
      .find { case (_, patterns) =>
        patterns.exists { pattern =>
          // Check if pattern fully contains the input
          val patternWords = pattern.split("\\s+")
          val consecutiveWords = patternWords
            .sliding(words.size)
            .exists(window => window.mkString(" ").contains(cleanedInput))

          // Or if input fully contains pattern with word boundaries
          cleanedInput.contains(s" $pattern ") ||
          cleanedInput.startsWith(s"$pattern ") ||
          cleanedInput.endsWith(s" $pattern") ||
          cleanedInput == pattern ||
          consecutiveWords
        }
      }
      .map(_._1)

    if (containsMatch.isDefined) return containsMatch

    // Step 3: Try partial matches with word analysis
    cleanedPatterns
      .find { case (_, patterns) =>
        patterns.exists { pattern =>
          val patternWords = pattern.split("\\s+").toSet
          val inputWords = words

          // Check if most words from pattern are in input
          val matchingWords = patternWords.intersect(inputWords).size
          matchingWords >= patternWords.size * 0.75 && patternWords.size >= 2 ||
          (patternWords.size > 2 && inputWords.size > 2 &&
            patternWords.intersect(inputWords).size >= 2)
        }
      }
      .map(_._1)
  }

  private val workoutKeywords = Set(
    "workout",
    "exercise",
    "training",
    "gym",
    "lift",
    "lifting",
    "muscle",
    "strength",
    "split",
    "routine",
    "program",
    "bodybuilding",
    "calisthenics",
    "martial arts",
    "strength training",
    "push",
    "pull",
    "legs",
    "upper",
    "lower",
    "chest",
    "back",
    "shoulders",
    "arms",
    "legs",
    "core",
    "abs",
    "help me train",
    "train",
    "training",
    "workout",
    "can you help me train"
  )

  def getRandomGreeting: String = {
    val name = User.name.getOrElse("").trim
    val nameWithSpace = if (name.nonEmpty) s"$name! " else ""
    val greetings = Seq(
      s"Hi there $nameWithSpace Ready to chat about fitness?",
      s"Hello $nameWithSpace What fitness topic would you like to explore today?",
      s"Hey $nameWithSpace Let's dive into some fitness knowledge!",
      s"Greetings $nameWithSpace What can I help you with today?",
      s"Welcome back $nameWithSpace Ready to learn something new?",
      s"Hi $nameWithSpace What fitness questions do you have?"
    )
    greetings(Random.nextInt(greetings.length))
  }
}
